//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserT()
        {
            this.Blogts = new HashSet<Blogt>();
        }
    
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public long MobileName { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blogt> Blogts { get; set; }
    }
}
