//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMVcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string pname { get; set; }
        public string pcno { get; set; }
        public Nullable<int> pbill { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> doctore_id { get; set; }
    }
}
